### ISSUE TITLE
V2 design review

### ISSUE THREAD

**Issue by cerquide** [Crowd4SDG/crowdnalysis#8]
@omulayim can you take a look at the [consensus.py](../blob/v2_refactoring/src/crowdnalysis/consensus.py) file on the v2_refactoring branch? I am designing a more structured interface to the Crowdnalysis models would be nice to have your opinion.

**Comment by omulayim** [comment]
Great idea to adhere to the formalisation in the [paper](https://www.mdpi.com/2227-7390/9/8/875). Shall we meet up for a couple of questions that I have.

**Comment by omulayim** [comment]
Submitted "Code with Me" session's code.

**Comment by cerquide** [comment]
I would consider this done
